services:

    cowrie:
    image: cowrie:cowrie
    environment:
      - COWRIE_TELNET_ENABLED=yes
    restart: always
    #volumes:
    #  - db_data:/var/lib/postgresql/data
    expose:
      - 2222:2222

